### ISSUE TITLE
Server Freezes with bad EEX

### ISSUE THREAD

**Issue by OvermindDL1** [phoenixframework/phoenix_live_reload#61] opened 2017-08-03 17:29 UTC
Had this code in an EEX file:
```elixir
<%= if @account[:local] %><% else %><% end %>
```
And when I hit save it caused the output terminal to *fill* with:
```elixir
warning: unexpected beginning of EEx tag "<%" on "<% else %>", please remove "" accordingly
  lib/my_server/templates/account/index.html.eex:25
```
It was filling so fast that the BEAM itself stopped responding to network input and nothing was working until I eventually had to `kill` it (not even Ctrl+C or any other escape commands were working).

Notice that the `do` was missing/forgotten off the `if`, once that was added back in then the system worked fine.  It should probably have some kind of throttle on it, or display an error message or something.  This only seemed to happen via the live reloader, not normal compilation, hence why posting it here instead of elixir-lang for EEX.

This is on RedHat7 over SSH with Elixir 1.5.1 and OTP 20.

**Comment by josevalim** [comment] 2021-08-29 20:08
Sorry, I should have followed up some time ago, but I cannot reproduce this. Has anyone else stumbled into this?

**Comment by josevalim** [comment] 2022-11-21 08:47
Closing for now. If anyone runs into this, please let us know how to reproduce it.

**Closed by josevalim** 2022-11-21 08:47 UTC
